@remoteUrl=http://127.0.0.1:5000/ 
#@remoteUrl=https://sleepy-depths-95784.herokuapp.com/
### Orders
GET {{remoteUrl}}/orders
Content-Type: application/json
###
POST {{remoteUrl}}/orders
Content-Type: application/json

{ 
    "cabin_id": "asdsad212321asdd21",
    "service_id": "1",
    "date": "2021-10-15"
}

###
PUT {{remoteUrl}}/orders
Content-Type: application/json

{
    "id": "17",
    "cabin_id": "6151c3a145a43cdf1fe5dd93",
    "service_id": 7,
    "date": "2021-10-15"

}

###
DELETE {{remoteUrl}}/orders
Content-Type: application/json

{
    "id": "1"
}